CREATE TABLE users(user_id SERIAL PRIMARY KEY,FIRST_NAME VARCHAR(100) NOT NULL,last_name VARCHAR(100) NOT NULL,email VARCHAR(255) UNIQUE);
CREATE TABLE ORDERS (order_id SERIAL PRIMARY KEY,user_id INT REFERENCES users(user_id),order_date DATE DEFAULT CURRENT_DATE);
